---
- name: Create keystone databases
  mysql_db: name=keystone state=present login_password={{ db_passwd  }}
  become: true 

- name: Create keystone user
  mysql_user: name=keystone password={{ keystone_passwd  }}  host={{ item  }} priv='keystone.*:ALL,GRANT' login_password={{ db_passwd  }} state=present 
  with_items:
  - '%'
  - localhost
  become: true

- name: Install keystone
  apt: name=keystone state=latest
  become: true

- name: Configure keystone connection
  lineinfile: dest=/etc/keystone/keystone.conf regexp='^connection' line='connection = mysql+pymysql://keystone:{{ keystone_passwd  }}@{{ controller_ip  }}/keystone'  state=present
  become: true

- name: Configure keystone provider
  lineinfile: dest=/etc/keystone/keystone.conf regexp='^#provider' line='provider = fernet' state=present
  become: true

- name: Keystone dbsync
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  become: true

- name: Initialize Fernet key(1)
  shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  become: true

- name: Initialize Fernet key(2)
  shell: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  become: true

- name: Initialize Fernet key(3)
  shell: "keystone-manage bootstrap --bootstrap-password {{ admin_passwd }} \
  --bootstrap-admin-url http://{{ controller_ip  }}:35357/v3/ \
  --bootstrap-internal-url http://{{ controller_ip }}:35357/v3/ \
  --bootstrap-public-url http://{{ controller_ip }}:5000/v3/ \
  --bootstrap-region-id RegionOne"
  become: true

- name: Configure apache
  file: path=/var/lib/keystone/keystone.db state=absent
  become: true

- name: Run script
  script: "./roles/newton_controller/scripts/create_keystone_environment.sh {{ controller_ip  }} none {{ admin_passwd }}" 
  become: true

- name: Create adminrc
  template: src=adminrc.j2 dest=~/adminrc
  become: true
